# Generated by Django 5.2 on 2025-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='-NA-', max_length=35),
        ),
    ]
