# Generated by Django 5.2 on 2025-04-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_profile_age_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='embedding',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
