# Generated by Django 5.2 on 2025-04-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_profile_embedding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='embedding',
            new_name='Facenet512_embedding',
        ),
        migrations.AddField(
            model_name='profile',
            name='ArcFace_embedding',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Dlib_embedding',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Facenet_embedding',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='VGGFace_embedding',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
