# Generated by Django 5.2 on 2025-04-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0004_rename_embedding_profile_facenet512_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ArcFace_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Dlib_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Facenet512_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Facenet_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='VGGFace_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
