# Generated by Django 5.2 on 2025-05-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_alter_profile_arcface_embedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='photos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
